/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./patches/tray";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { openModal } from "@utils/modal";
import { onceReady } from "@webpack";
import { React, VoiceActions } from "@webpack/common";

import { SecurityModal } from "./components/SecurityModal";
import SettingsUi from "./components/settings/Settings";
import { VesktopLogger } from "./logger";
import { Settings } from "./settings";
import { localStorage } from "./utils";
export { Settings };

import type SettingsPlugin from "@plugins/_core/settings";
import { VesktopSettingsIcon } from "shared/icons";

VesktopLogger.log("read if cute :3");
VesktopLogger.log(`werathcord v${VesktopNative.app.getVersion()}`);

const { customEntries, customSections } = Vencord.Plugins.plugins.Settings as any as typeof SettingsPlugin;

customEntries.push({
    key: "werathcord_werathcord_settings",
    title: "werathcord Settings",
    Component: SettingsUi,
    Icon: VesktopSettingsIcon
});

customSections.push(() => ({
    section: "werathcordSettings",
    label: "werathcord Settings",
    element: SettingsUi,
    className: "vc-werathcord-settings"
}));

VesktopNative.voice.onToggleSelfMute(() => VoiceActions.toggleSelfMute());
VesktopNative.voice.onToggleSelfDeaf(() => VoiceActions.toggleSelfDeaf());


// TODO: remove this legacy workaround once some time has passed
if (!Vencord.Api.Styles.vencordRootNode) {
    const style = document.createElement("style");
    style.id = "vesktop-css-core";
    VesktopNative.app.getRendererCss().then(css => (style.textContent = css));
    document.addEventListener("DOMContentLoaded", () => document.documentElement.append(style), { once: true });
}
